name: Build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build changed documents
      uses: ./.github/actions/hse-tex-build
      env: 
        CHECK_DIFF: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Documents
        path: .pdf/**/*.pdf
